# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

# Folder Structure
source: ./source

# sass_dir: source/css

contentful:
  spaces:
    - cases: # Jekyll _data folder identifier - Required
        space: aiyxen77s4uc         # Required
        access_token: 19fe7171bb04c2c91672bd62917606d1603fdd0dd6a9e83fd29895f279cbd1f0
        base_path: ./source         # Optional - Defaults to Current directory
        destination: ./source/_data/contentful/spaces # Optional - Defaults to _data/contentful/spaces

page_gen:
  - data: 'contentful.spaces.cases.datacollaborative'
    template: 'case_template'
    name: 'caseStudy'
    dir: 'cases'
    # extension: 'html'
